CREATE TABLE role
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(20) NOT NULL
);

CREATE TABLE "user"
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(40)  NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id  INT REFERENCES role (id)
);

CREATE TABLE gender
(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gender VARCHAR(20) NOT NULL
);

CREATE TABLE country
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL
);

CREATE TABLE region
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(32)                 NOT NULL,
    country_id INT REFERENCES country (id) NOT NULL
);

CREATE TABLE local_area
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(32)                NOT NULL,
    region_id INT REFERENCES region (id) NOT NULL
);

CREATE TABLE city
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(32)                    NOT NULL,
    local_area_id INT REFERENCES local_area (id) NOT NULL
);

CREATE TABLE profile
(
    id        INT REFERENCES "user" (id) PRIMARY KEY,
    name      VARCHAR(63)                NOT NULL,
    age       INT                        NOT NULL,
    gender_id INT REFERENCES gender (id) NOT NULL,
    text      TEXT                       NOT NULL,
    city_id   INT REFERENCES city (id)   NOT NULL
);

CREATE TABLE music
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(32)                 NOT NULL,
    author     VARCHAR(32)                 NOT NULL,
    file_path  VARCHAR(128)                NOT NULL,
    profile_id INT REFERENCES profile (id) NOT NULL
);

ALTER TABLE profile
    ADD COLUMN preview_music_id INT REFERENCES music (id);

CREATE TABLE instrument
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL
);

CREATE TABLE profile_instrument
(
    profile_id    INT REFERENCES profile (id)    NOT NULL,
    instrument_id INT REFERENCES instrument (id) NOT NULL
);

CREATE TABLE speciality
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL
);

CREATE TABLE profile_speciality
(
    profile_id    INT REFERENCES profile (id)    NOT NULL,
    speciality_id INT REFERENCES speciality (id) NOT NULL
);

